src/main/java/com/bogdansukonnov/eclinicinfo/dto/EventInfoDto.java
package com.bogdansukonnov.eclinicinfo.dto;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class EventInfoDto {
    private Long eventId;
    private String time;
    private String treatmentType;
    private String treatment;
    private String patient;
}

src/main/java/com/bogdansukonnov/eclinicinfo/dto/EventInfoListDto.java
package com.bogdansukonnov.eclinicinfo.dto;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
public class EventInfoListDto {

    private List<EventInfoDto> events = new ArrayList<>();

}

src/main/java/com/bogdansukonnov/eclinicinfo/entity/Event.java
package com.bogdansukonnov.eclinicinfo.entity;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Event {

    private Long eventId;
    private String time;
    private String treatmentType;
    private String treatment;
    private String patient;

}

src/main/java/com/bogdansukonnov/eclinicinfo/EventsBean.java
package com.bogdansukonnov.eclinicinfo;

import com.bogdansukonnov.eclinicinfo.config.PropertiesFromFile;
import com.bogdansukonnov.eclinicinfo.converter.EventConverter;
import com.bogdansukonnov.eclinicinfo.dto.EventInfoListDto;
import com.bogdansukonnov.eclinicinfo.entity.Event;
import com.bogdansukonnov.eclinicinfo.service.EventService;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import javax.faces.push.Push;
import javax.faces.push.PushContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Logger;
import java.util.stream.Collectors;

@Named
@ApplicationScoped
public class EventsBean {

    private List<Event> events = new ArrayList<>();
    private String updated = "never";

    @Inject
    @PropertiesFromFile
    private Properties appProperties;

    @Inject
    private EventConverter converter;

    @Inject
    @Push
    private PushContext push;

    @Inject
    private Logger log;

    public void onEventInfoListUpdate(@Observes EventInfoListDto eventsDTO) {
        log.info("fired event on EventInfoListDto");
        updated = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        events.clear();
        if (eventsDTO != null) {
            events = eventsDTO.getEvents().stream()
                    .map(dto -> converter.toEvent(dto))
                    .collect(Collectors.toList());
        }
        push.send("updateEvents");
    }

    public List<Event> getEvents() {
        return events;
    }

    public String getCompanyName() {
        return appProperties.getProperty("company.name");
    }

    public  String getUpdated() {
        return updated;
    }

}

src/main/java/com/bogdansukonnov/eclinicinfo/message/JMSListenerBean.java
package com.bogdansukonnov.eclinicinfo.message;

import com.bogdansukonnov.eclinicinfo.service.EventService;
import org.jboss.ejb3.annotation.ResourceAdapter;

import javax.ejb.ActivationConfigProperty;
import javax.ejb.MessageDriven;
import javax.inject.Inject;
import javax.jms.Message;
import javax.jms.MessageListener;
import java.util.logging.Logger;

@ResourceAdapter("remote-artemis")
@MessageDriven(name = "EventChangeListener", activationConfig = {
        @ActivationConfigProperty(propertyName = "useJNDI", propertyValue = "false"),
        @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Topic"),
        @ActivationConfigProperty(propertyName = "destination", propertyValue = "event-update"),
        @ActivationConfigProperty(propertyName = "acknowledgeMode", propertyValue = "Auto-acknowledge")})
public class JMSListenerBean implements MessageListener {

    @Inject
    private Logger log;

    @Inject
    EventService eventService;

    public JMSListenerBean() {
    }

    @Override
    public void onMessage(Message message) {
        log.info("message received " + log.getClass());
        eventService.updateEvents();
    }

}

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:composition template="/template.xhtml">

        <ui:define name="title">eClinic-info</ui:define>
        <ui:define name="head">eClinic-info</ui:define>
        <ui:define name="content">

            <div id="header">
                <h2>Today</h2>
                <p > updated at <h:outputText id="updated" value="#{eventsBean.updated}" /></p>
            </div>

            <h:dataTable id="events" value="#{eventsBean.events}" var="event" styleClass="table table-striped">
                <h:column>
                    <f:facet name="header">Time</f:facet>
                    #{event.time}
                </h:column>
                <h:column>
                    <f:facet name="header">Patient</f:facet>
                    #{event.patient}
                </h:column>
                <h:column>
                    <f:facet name="header">Type</f:facet>
                    #{event.treatmentType}
                </h:column>
                <h:column>
                    <f:facet name="header">Treatment</f:facet>
                    #{event.treatment}
                </h:column>
            </h:dataTable>

            <h:form>
                <f:websocket channel="push">
                    <f:ajax event="updateEvents" render="events updated"/>
                </f:websocket>
            </h:form>

        </ui:define>

    </ui:composition>
</html>

src/main/webapp/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <link rel="icon" type="image/png"
              href="#{request.contextPath}/resources/images/favicon-package/favicon-32x32.png"/>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="eclinic-info.css"/>
        <title>#{eventsBean.companyName} today</title>
    </h:head>

    <body>
        <div class="main-header navbar navbar-expand-lg navbar-dark">
            <a id="main-header-brand" class="navbar-brand" href="/">
                <h:graphicImage value="resources/images/logo.svg" alt="logo" height="32" />
                <ui:insert name="companyName">#{eventsBean.companyName}</ui:insert>
            </a>
        </div>
        <div id="container" class="container-fluid">

            <div id="space">
                <p></p>
            </div>

            <div id="content">
                <ui:insert name="content"/>
            </div>
        </div>
    </body>
</html>